---
title: "COVID-19 Data"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: yeti
    orientation: rows
    social: [ "twitter", "facebook"]
runtime: shiny
---
<style type="text/css">

.chart-title {  /* chart_title  */
   font-size: 20px;

</style>


Countries
=====================================     

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
library(shinyBS)
library(shinyjs)

data <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"))

useShinyjs(rmd = TRUE)

countries <- sort(unique(data$Country.Region))[-c(which(sort(unique(data$Country.Region)) == "China"),
                                                  which(sort(unique(data$Country.Region)) == "US"),
                                                  which(sort(unique(data$Country.Region)) == "Australia"))]  
selectInput("Country", label = h5("Country"),
            choices =  countries,
            selected = "Spain")

```


Column {data-height=200}
-------------------------------------

```{r}
library(plotly)
library(shinydashboard)

data_cases   <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"))
data_recover <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"))
data_deaths  <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"))



```


```{r}
renderTable({
  df <- data.frame(cases =  tail(as.numeric(data_cases[which(data_cases$Country.Region == input$Country), 5:ncol(data_cases) ]), n = 1), 
             recover = tail(as.numeric(data_recover[which(data_recover$Country.Region == input$Country), 5:ncol(data_recover) ]), n = 1),
             deaths = tail(as.numeric(data_deaths[which(data_deaths$Country.Region == input$Country), 5:ncol(data_deaths) ]), n = 1))
  
  colnames(df) <- c("New cases (yesterday)", "Recovered (yesterday)", "Deaths (yesterday)")
  df
})

```




Column {data-width=600}
-------------------------------------

### Confirmed cases
    
```{r}
# library(plotly)

renderPlot({
plot(as.numeric(data_cases[which(data_cases$Country.Region == input$Country),
                           5:ncol(data_cases) ]), type = "l", col = "red", lwd = 2, xlab = "", ylab = "")
})

# Triying to use plotly
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Country.Region == input$Country), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- as.numeric(data[which(data$Country.Region == input$Country), 5:ncol(data) ])
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# 
# fig


```
 
 

### Log confirmed cases
```{r}

renderPlot({
plot(log(as.numeric(data_cases[which(data_cases$Country.Region == input$Country),
                               5:ncol(data_cases) ])), type = "l", col = "green", lwd = 2, xlab = "", ylab = "")
})

# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# fig

```
 
    

Column {data-width=600}
-------------------------------------

### Recovered

```{r}
renderPlot({
plot(as.numeric(data_recover[which(data_recover$Country.Region == input$Country),
                             5:ncol(data_recover) ]), type = "l", col = "blue", lwd = 2, xlab = "", ylab = "")
})
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# fig

```

### Deceased
```{r, echo = FALSE}
renderPlot({
plot(as.numeric(data_deaths[which(data_deaths$Country.Region == input$Country),
                            5:ncol(data_deaths) ]), type = "l", col = "red", lwd = 2, xlab = "", ylab = "")
})
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Country.Region == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))

# fig
```



State-Provinces
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------
```{r}
library(shinyBS)
library(shinyjs)

data <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"))

useShinyjs(rmd = TRUE)
    
selectInput("Province_State", label = h5("Province-State"),
            choices =  sort(data$Province.State),
            selected = "Victoria")

```


Column {data-height=200}
-------------------------------------

```{r}
library(plotly)
library(shinydashboard)

data_cases   <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv"))
data_recover <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv"))
data_deaths  <- read.csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv"))



```


```{r}
renderTable({
  df <- data.frame(cases =  tail(as.numeric(data_cases[which(data_cases$Province.State == input$Province_State), 5:ncol(data_cases) ]), n = 1), 
             recover = tail(as.numeric(data_recover[which(data_recover$Province.State == input$Province_State), 5:ncol(data_recover) ]), n = 1),
             deaths = tail(as.numeric(data_deaths[which(data_deaths$Province.State == input$Province_State), 5:ncol(data_deaths) ]), n = 1))
  
  colnames(df) <- c("New cases (yesterday)", "Recovered (yesterday)", "Deaths (yesterday)")
  df
})

```




Column {data-width=600}
-------------------------------------

### Confirmed cases
    
```{r}
# library(plotly)

renderPlot({
plot(as.numeric(data_cases[which(data_cases$Province.State == input$Province_State),
                           5:ncol(data_cases) ]), type = "l", col = "red", lwd = 2, xlab = "", ylab = "")
})

# Triying to use plotly
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Province.State == input$Province_State), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- as.numeric(data[which(data$Province.State == input$Province_State), 5:ncol(data) ])
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# 
# fig


```
 
 

### Log confirmed cases
```{r}

renderPlot({
plot(log(as.numeric(data_cases[which(data_cases$Province.State == input$Province_State),
                               5:ncol(data_cases) ])), type = "l", col = "green", lwd = 2, xlab = "", ylab = "")
})

# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# fig

```
 
    

Column {data-width=600}
-------------------------------------

### Recovered

```{r}
renderPlot({
plot(as.numeric(data_recover[which(data_recover$Province.State == input$Province_State),
                             5:ncol(data_recover) ]), type = "l", col = "blue", lwd = 2, xlab = "", ylab = "")
})
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))
# 
# fig

```

### Deceased
```{r, echo = FALSE}
renderPlot({
plot(as.numeric(data_deaths[which(data_deaths$Province.State == input$Province_State),
                            5:ncol(data_deaths) ]), type = "l", col = "red", lwd = 2, xlab = "", ylab = "")
})
# today <- Sys.Date() - 1
# tm <- seq(from = length(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ])), to =  1, by = -1)
# x <- today - (tm - 1)
# y <- log(as.numeric(data[which(data$Province.State == "Spain"), 5:ncol(data) ]))
# fig <- plot_ly(x = ~x, y = ~y, mode = 'lines', text = paste(tm, "days from today"))

# fig
```